export default [
  "Ashburn, US",
  "Atlanta, US",
  "Boston, US",
  "Buffalo, US",
  "Calgary, CA",
  "Charlotte, US",
  "Chicago, US",
  "Columbus, US",
  "Dallas, US",
  "Denver, US",
  "Detroit, US",
  "Honolulu, US",
  "Houston, US",
  "Indianapolis, US",
  "Jacksonville, US",
  "Kansas City, US",
  "Las Vegas, US",
  "Los Angeles, US",
  "Mcallen, US",
  "Memphis, US",
  "Miami, US",
  "Minneapolis, US",
  "Montgomery, US",
  "Montréal, CA",
  "Nashville, US",
  "Newark, US",
  "Norfolk, US",
  "Omaha, US",
  "Ottawa, CA",
  "Philadelphia, US",
  "Phoenix, US",
  "Pittsburgh, US",
  "Portland, US",
  "Richmond, US",
  "Sacramento, US",
  "Salt Lake City, US",
  "San Diego, US",
  "San Jose, US",
  "Saskatoon, CA",
  "Seattle, US",
  "St. Louis, US",
  "Tallahassee, US",
  "Tampa, US",
  "Toronto, CA",
  "Vancouver, CA",
  "Winnipeg, CA",
  "Arica, CL",
  "Asuncion, PY",
  "Bogota, CO",
  "Buenos Aires, AR",
  "Cordoba, AR",
  "Curitiba, BR",
  "Fortaleza, BR",
  "Guatemala City, GT",
  "Lima, PE",
  "Medellín, CO",
  "Mexico City, MX",
  "Neuquen, AR",
  "Panama City, PA",
  "Paramaribo, SR",
  "Port-Au-Prince, HT",
  "Porto Alegre, BR",
  "Queretaro, MX",
  "Quito, EC",
  "Rio de Janeiro, BR",
  "St George's, GD",
  "São Paulo, BR",
  "Tegucigalpa, HN",
  "Valparaíso, CL",
  "Willemstad, CW",
  "Adelaide, AU",
  "Auckland, NZ",
  "Brisbane, AU",
  "Melbourne, AU",
  "Noumea, NC",
  "Perth, AU",
  "Sydney, AU",
  "Amman, JO",
  "Baghdad, IQ",
  "Baku, AZ",
  "Beirut, LB",
  "Doha, QA",
  "Dubai, AE",
  "Kuwait City, KW",
  "Manama, BH",
  "Muscat, OM",
  "Ramallah, PS",
  "Riyadh, SA",
  "Tel Aviv, IL",
  "Amsterdam, NL",
  "Athens, GR",
  "Barcelona, ES",
  "Belgrade, RS",
  "Berlin, DE",
  "Brussels, BE",
  "Bucharest, RO",
  "Budapest, HU",
  "Chișinău, MD",
  "Copenhagen, DK",
  "Cork, IE",
  "Dublin, IE",
  "Düsseldorf, DE",
  "Edinburgh, GB",
  "Frankfurt, DE",
  "Geneva, CH",
  "Gothenburg, SE",
  "Hamburg, DE",
  "Helsinki, FI",
  "Istanbul, TR",
  "Kyiv, UA",
  "Lisbon, PT",
  "London, GB",
  "Luxembourg City, LU",
  "Madrid, ES",
  "Manchester, GB",
  "Marseille, FR",
  "Milan, IT",
  "Moscow, RU",
  "Munich, DE",
  "Nicosia, CY",
  "Oslo, NO",
  "Paris, FR",
  "Prague, CZ",
  "Reykjavík, IS",
  "Riga, LV",
  "Rome, IT",
  "Sofia, BG",
  "St. Petersburg, RU",
  "Stockholm, SE",
  "Tallinn, EE",
  "Thessaloniki, GR",
  "Vienna, AT",
  "Vilnius, LT",
  "Warsaw, PL",
  "Zagreb, HR",
  "Zürich, CH",
  "Antananarivo, MG",
  "Cape Town, ZA",
  "Casablanca, MA",
  "Dakar, SN",
  "Dar Es Salaam, TZ",
  "Djibouti, DJ",
  "Durban, ZA",
  "Johannesburg, ZA",
  "Kigali, RW",
  "Lagos, NG",
  "Luanda, AO",
  "Maputo, MZ",
  "Mombasa, KE",
  "Monrovia, LR",
  "Port Louis, MU",
  "Reunion, FR",
  "Bandar Seri Begawan, BN",
  "Bangkok, TH",
  "Bengaluru, IN",
  "Cebu City, PH",
  "Chennai, IN",
  "Chittagong, BD",
  "Colombo, LK",
  "Dhaka, BD",
  "Hanoi, VN",
  "Ho Chi Minh City, VN",
  "Hong Kong, CN",
  "Hyderabad, IN",
  "Islamabad, PK",
  "Jakarta, ID",
  "Johor Bahru, MY",
  "Karachi, PK",
  "Kathmandu, NP",
  "Kolkata, IN",
  "Kuala Lumpur, MY",
  "Lahore, PK",
  "Macau, MO",
  "Male, MV",
  "Manila, PH",
  "Mumbai, IN",
  "Nagpur, IN",
  "New Delhi, IN",
  "Osaka, JP",
  "Phnom Penh, KH",
  "Seoul, KR",
  "Singapore, SG",
  "Taipei, TW",
  "Thimphu, BT",
  "Tokyo, JP",
  "Ulaanbaatar, MN",
  "Vientiane, LA",
  "Yerevan, AM",
  "Chongqing, CN",
  "Dongguan, CN",
  "Guangzhou, CN",
  "Jinan, CN",
  "Nanning, CN",
  "Ningbo, CN",
  "Shanghai, CN",
  "Shenyang, CN",
  "Shijiazhuang, CN",
  "Suzhou, CN",
  "Tianjin, CN",
  "Tsingtao, CN",
  "Wuhan, CN",
  "Wuxi, CN",
  "Xian, CN",
  "Zhengzhou, CN",
  "Zhuzhou, CN"
]